config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
  end

  authenticated :user do
    root :to => 'projects#index', as: :authenticated_root
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    alias_action :create, :update, :destroy, to: :cud
      #user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
        can :cud, :Project
        can :cud, :Task do |task|
            task.try(:user) == user
        end
        can :cud, :Comment, user_id: user.id
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tasks
  belongs_to :user
  validates :user_id, presence: true
  validates :body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :name, presence: true,
            length: { minimum: 5 }
  validates :summary, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :comments
  belongs_to :projects
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :task
  has_many      :comments
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include CanCan::ControllerAdditions
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied!"
    redirect_to :back
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  protect_from_forgery with: :exception
  load_and_authorize_resource

  def edit
    @project = Project.find(@task)
  end

  def update
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to project_task_path(@task)
    else
      render 'edit'
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(comment_params.merge(:user_id => current_user.id))
    if @comment.save
      redirect_to project_task_path(@project, @task)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to project_task_path(@project, @task)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  protect_from_forgery with: :exception
  load_and_authorize_resource

  def create
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  protect_from_forgery with: :exception
  load_and_authorize_resource

  def show
    @project = Project.find(params[:project_id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to project_task_path(@task)
    else
      render 'edit'
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    if @task.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_path(@project)
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :status, :user_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for ([@project, @task, comment]) do |f| %>
    <p>
      <%= f.label :"Comment" %><br>
      <%= f.text_field :body %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </p>
    <p>
      <%= f.submit :class => "btn btn-default" %>
    </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for ([@project, @task, @comment]) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2>
            <%= pluralize(@comment.errors.count, "error") %> prohibited
            this task from being saved:
          </h2>
          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :"Comment" %><br>
      <%= f.text_field :body %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </p>
    <p>
      <%= f.submit :class => "btn btn-default" %>
    </p>
<% end %>

<td><%= link_to 'Back', project_task_path(@project, @task), { :class => "btn btn-default" } %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<div style="margin-left: 30%">
<%= form_for @project do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p class="input-group">
      <%= f.label :"Project name" %><br>
      <%= f.text_field :name, { :class => "form-control", :type => "text"} %><br>
      <%= f.label :"Description" %><br>
      <%= f.text_field :summary, { :class => "form-control", :type => "text"} %>
    </p>

    <p class="form-group">
      <%= f.label :"Start date" %><br>
      <%= f.text_field :start_date, { :class => "btn btn-default", :type => "date", } %><br>
      <%= f.label :"End date" %><br>
      <%= f.text_field :end_date, { :class => "btn btn-default", :type => "date"}%>
    </p>

    <p>
      <%= f.submit :class => "btn btn-default" %>
    </p>
<% end %>
</div>

app/views/projects/_project.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
<p>
  <strong>Summary:</strong>
  <%= @project.summary %>
</p>
<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>
<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>

app/views/projects/edit.html.erb
<%= render 'welcome/header' %>
<h1>Editing project</h1>

<%= render 'form' %>

<td><%= link_to 'Back', projects_path, { :class => "btn btn-default" } %></td>

app/views/projects/index.html.erb
<%= render 'welcome/header' %>
<h1>Listing projects</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
  </tr>

  <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.summary %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td class="btn-group">
        <%= link_to 'Show', project_path(project), { :class => "btn btn-default" } %>
        <% if can? :update, project %>
        <%= link_to 'Edit', edit_project_path(project), { :class => "btn btn-default" } %>
        <% end %>
        <% if can? :destroy, project %>
        <%= link_to 'Destroy', project_path(project),
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    :class => "btn btn-default" %>
        <% end %>

      </tr>
  <% end %>
</table>
<td><%= link_to 'New project', new_project_path, { :class => "btn btn-default" } %></td>

app/views/projects/new.html.erb
<%= render 'welcome/header' %>
<h1>New project</h1>

<%= render 'form' %>

<td><%= link_to 'Back', projects_path, { :class => "btn btn-default" } %></td>

app/views/projects/show.html.erb
<%= render 'welcome/header' %>
<%= render 'project' %>

<h2>Tasks</h2>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Assign</th>
    <th></th>
  </tr>

  <% @project.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.user.email %></td>
        <td class="btn-group">
          <%= link_to 'Show', project_task_path(@project, task), { :class => "btn btn-default" } %>
          <% if can? :update, task %>
          <%= link_to 'Edit', edit_project_task_path(@project, task), { :class => "btn btn-default" } %>
          <% end %>
          <% if can? :destroy, task %>
          <%= link_to 'Destroy', project_task_path(@project, task),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      :class => "btn btn-default" %>
          <% end %>

      </tr>
  <% end %>
</table>

<h3>Add a task:</h3>
<%= link_to 'New task', new_project_task_path(@project), { :class => "btn btn-default" } %>

<td><%= link_to 'Back', projects_path, { :class => "btn btn-default" } %></td>

app/views/tasks/_task.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

app/views/tasks/_task_form.html.erb
<%= form_for ([@project, @task]) do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2>
            <%= pluralize(@task.errors.count, "error") %> prohibited
            this task from being saved:
          </h2>
          <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :"Title" %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :"Description" %><br>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :"Status" %><br>
      <%= f.select :status, options_for_select(["new", "in progress", "done" ]) %>
    </p>
    <p>
      <% if current_user.admin %>
          <%= f.label :"Assign" %><br>
          <%= f.select :user_id, User.all.collect {|p| [p.email, p.id]} %>
      <% else %>
          <%= f.hidden_field :user_id, value: current_user.id %>
      <% end %>
    </p>
    <p>
      <%= f.submit :class => "btn btn-default" %>
    </p>

<% end %>

app/views/tasks/edit.html.erb
<%= render 'welcome/header' %>
<h1>Editing task</h1>

<%= render 'task_form' %>

<td><%= link_to 'Back', project_task_path(@project, @task), { :class => "btn btn-default" } %></td>

app/views/tasks/new.html.erb
<%= render 'welcome/header' %>
<h1>New task</h1>

<%= render 'task_form' %>

<td><%= link_to 'Back', project_path(@project), { :class => "btn btn-default" } %></td>

app/views/tasks/show.html.erb
<%= render 'welcome/header' %>
<%= render 'task' %>

<h2>Comments</h2>
<table class="table">
  <tr>
    <th>Author</th>
    <th>Comment</th>
    <th></th>
  </tr>

  <% @task.comments.each do |comment| %>
      <tr>
        <td><%= comment.user.email %></td>
        <td><%= comment.body %></td>
        <td class="btn-group">
          <%= link_to 'Edit', edit_project_task_comment_path(@project, @task, comment), { :class => "btn btn-default" } %>
          <%= link_to 'Destroy', project_task_comment_path(@project, @task, comment),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      :class => "btn btn-default" %>

      </tr>
  <% end %>
</table>

<%= render partial: 'comments/comment_form', locals: {comment: @task.comments.build} %>

<td><%= link_to 'Back', project_path(@project), { :class => "btn btn-default" } %></td>

app/views/welcome/_header.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <%= link_to 'Projects management', root_path, { :class => "navbar-brand" }%>
  </div>
  <% if user_signed_in? %>
      <div class="navbar-right" style="padding-right: 30px">
        <span>Здравствуйте, <%= current_user.email %></span>
        <%= link_to 'Выйти', destroy_user_session_path, { :class => "btn btn-default navbar-btn", :method => :delete }%>
      </div>
  <% else %>
      <div class="btn-group navbar-right" role="group" aria-label="..." style="padding-right: 30px">
        <%= link_to 'Войти', new_user_session_path, { :class => "btn btn-default" }%>
        <%= link_to 'Зарегистрироваться', new_user_registration_path, { :class => "btn btn-default navbar-btn" } %>
      </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<%= render 'header' %>
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'Проекты', projects_path, { :class => "btn btn-default" } %>